"""Tests for generators."""

import json
from pathlib import Path

import pytest

from agent_scaffold.generators import (
    get_generator,
    load_generated_tracking,
    save_generated_tracking,
)
from agent_scaffold.generators.copilot import CopilotGenerator
from agent_scaffold.generators.opencode import OpenCodeGenerator
from agent_scaffold.manifest import load_manifest


class TestGeneratorRegistry:
    """Tests for generator registration and lookup."""

    def test_get_opencode_generator(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]

        generator = get_generator("opencode", target_config, manifest, tmp_project)

        assert generator is not None
        assert isinstance(generator, OpenCodeGenerator)

    def test_get_copilot_vscode_generator(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]

        generator = get_generator("copilot-vscode", target_config, manifest, tmp_project)

        assert generator is not None
        assert isinstance(generator, CopilotGenerator)
        assert generator.is_vscode is True

    def test_get_copilot_cli_generator(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-cli"]

        generator = get_generator("copilot-cli", target_config, manifest, tmp_project)

        assert generator is not None
        assert isinstance(generator, CopilotGenerator)
        assert generator.is_vscode is False


class TestGeneratedTracking:
    """Tests for generated file tracking."""

    def test_load_empty_tracking(self, tmp_path: Path):
        result = load_generated_tracking(tmp_path)
        assert result == set()

    def test_save_and_load_tracking(self, tmp_path: Path):
        files = {"file1.md", "dir/file2.md", "another/file3.json"}

        save_generated_tracking(tmp_path, files)
        loaded = load_generated_tracking(tmp_path)

        assert loaded == files

    def test_tracking_file_location(self, tmp_path: Path):
        save_generated_tracking(tmp_path, {"test.md"})

        tracking_path = tmp_path / ".agents" / ".generated.json"
        assert tracking_path.exists()

    def test_tracking_file_format(self, tmp_path: Path):
        files = {"a.md", "b.md"}
        save_generated_tracking(tmp_path, files)

        tracking_path = tmp_path / ".agents" / ".generated.json"
        data = json.loads(tracking_path.read_text())

        assert data["version"] == 1
        assert "files" in data
        assert sorted(data["files"]) == ["a.md", "b.md"]


class TestOpenCodeGenerator:
    """Tests for the OpenCode generator."""

    def test_list_generated_files(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        files = generator.list_generated_files()

        assert tmp_project / "opencode.json" in files
        assert tmp_project / "AGENTS.md" in files

    def test_generate_opencode_json(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        generator.generate()

        config_path = tmp_project / "opencode.json"
        assert config_path.exists()

        config = json.loads(config_path.read_text())
        assert "$schema" in config
        assert "instructions" in config
        assert "agent.reviewer" in config

    def test_generate_opencode_json_agent_config(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        generator.generate()

        config = json.loads((tmp_project / "opencode.json").read_text())
        agent_config = config["agent.reviewer"]

        assert "prompt" in agent_config
        assert agent_config["prompt"]["file"] == "./.agents/agents/reviewer.md"

    def test_generate_agents_md(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        generator.generate()

        agents_md_path = tmp_project / "AGENTS.md"
        assert agents_md_path.exists()

        content = agents_md_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert "## Instructions" in content
        assert "## Agents" in content
        assert "reviewer" in content

    def test_generate_dry_run(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        files = generator.generate(dry_run=True)

        assert len(files) == 2
        assert not (tmp_project / "opencode.json").exists()
        assert not (tmp_project / "AGENTS.md").exists()

    def test_banner_html_style(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        banner = generator.banner("html")
        assert banner.startswith("<!--")
        assert "Generated by agent-scaffold" in banner

    def test_generate_opencode_json_with_commands(self, tmp_project: Path):
        """Test that commands are included in opencode.json."""
        from agent_scaffold.manifest import create_default_manifest, save_manifest
        from agent_scaffold.models import CommandArtifact

        # Create a manifest with commands
        manifest = create_default_manifest("test-project")
        manifest.artifacts.commands.append(
            CommandArtifact(
                id="test",
                canonical_file=".agents/commands/test.md",
                description="Run tests",
                user_input="optional",
            )
        )
        manifest.artifacts.commands.append(
            CommandArtifact(
                id="search",
                canonical_file=".agents/commands/search.md",
                description="Search code",
                user_input="required",
            )
        )
        save_manifest(tmp_project, manifest)

        # Generate
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)
        generator.generate()

        # Verify
        config = json.loads((tmp_project / "opencode.json").read_text())
        assert "command.test" in config
        assert config["command.test"]["description"] == "Run tests"
        assert config["command.test"]["template"]["file"] == "./.agents/commands/test.md"
        # Optional user input should not be included
        assert "userInput" not in config["command.test"]

        assert "command.search" in config
        assert config["command.search"]["userInput"] == "required"

    def test_generate_opencode_json_commands_sorted(self, tmp_project: Path):
        """Test that commands are sorted alphabetically."""
        from agent_scaffold.manifest import create_default_manifest, save_manifest
        from agent_scaffold.models import CommandArtifact

        manifest = create_default_manifest("test-project")
        manifest.artifacts.commands.append(
            CommandArtifact(id="zebra", canonical_file=".agents/commands/zebra.md")
        )
        manifest.artifacts.commands.append(
            CommandArtifact(id="alpha", canonical_file=".agents/commands/alpha.md")
        )
        manifest.artifacts.commands.append(
            CommandArtifact(id="beta", canonical_file=".agents/commands/beta.md")
        )
        save_manifest(tmp_project, manifest)

        # Generate
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)
        generator.generate()

        # Verify order
        config = json.loads((tmp_project / "opencode.json").read_text())
        command_keys = [k for k in config.keys() if k.startswith("command.")]
        assert command_keys == ["command.alpha", "command.beta", "command.zebra"]


class TestCopilotGenerator:
    """Tests for the Copilot generator."""

    def test_list_generated_files_vscode(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        files = generator.list_generated_files()

        # Should include prompts, agents, instructions, skills
        file_strs = [str(f) for f in files]
        assert any("explain-code.prompt.md" in f for f in file_strs)
        assert any("reviewer.agent.md" in f for f in file_strs)
        assert any("typescript.instructions.md" in f for f in file_strs)
        assert any("api-builder" in f and "SKILL.md" in f for f in file_strs)

    def test_list_generated_files_cli_no_prompts(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-cli"]
        generator = CopilotGenerator("copilot-cli", target_config, manifest, tmp_project)

        files = generator.list_generated_files()

        # CLI should not have prompts
        file_strs = [str(f) for f in files]
        assert not any(".prompt.md" in f for f in file_strs)
        # But should have agents
        assert any("reviewer.agent.md" in f for f in file_strs)

    def test_generate_prompt_file(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        generator.generate()

        prompt_path = tmp_project / ".github" / "prompts" / "explain-code.prompt.md"
        assert prompt_path.exists()

        content = prompt_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert "name: explain-code" in content
        assert "Follow instructions in" in content
        assert ".agents/prompts/explain-code.md" in content

    def test_generate_agent_file(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        generator.generate()

        agent_path = tmp_project / ".github" / "agents" / "reviewer.agent.md"
        assert agent_path.exists()

        content = agent_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert "name: reviewer" in content
        assert "description: Code review specialist" in content

    def test_generate_instruction_file(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        generator.generate()

        instruction_path = (
            tmp_project / ".github" / "instructions" / "typescript.instructions.md"
        )
        assert instruction_path.exists()

        content = instruction_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert 'applyTo: "**/*.ts"' in content

    def test_generate_repo_instructions(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        generator.generate()

        repo_instructions_path = tmp_project / ".github" / "copilot-instructions.md"
        assert repo_instructions_path.exists()

        content = repo_instructions_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert "repo-default" in content

    def test_generate_skill_file(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        generator.generate()

        skill_path = tmp_project / ".github" / "skills" / "api-builder" / "SKILL.md"
        assert skill_path.exists()

        content = skill_path.read_text()
        assert "Generated by agent-scaffold" in content
        assert "name: API Builder" in content

    def test_generate_dry_run(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        files = generator.generate(dry_run=True)

        assert len(files) > 0
        assert not (tmp_project / ".github" / "prompts").exists()

    def test_disabled_artifact_not_generated(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)

        # Disable the prompt for copilot-vscode
        manifest.artifacts.prompts[0].targets["copilot-vscode"].enabled = False

        target_config = manifest.targets["copilot-vscode"]
        generator = CopilotGenerator("copilot-vscode", target_config, manifest, tmp_project)

        files = generator.list_generated_files()
        file_strs = [str(f) for f in files]

        assert not any("explain-code.prompt.md" in f for f in file_strs)


class TestGeneratorOutput:
    """Integration tests for generator output."""

    def test_all_targets_generate(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)

        for target_name, target_config in manifest.targets.items():
            if not target_config.enabled:
                continue

            generator = get_generator(target_name, target_config, manifest, tmp_project)
            if generator:
                files = generator.generate()
                assert len(files) > 0, f"No files generated for {target_name}"

    def test_generated_files_are_valid(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        generator.generate()

        # Verify opencode.json is valid JSON
        config_path = tmp_project / "opencode.json"
        config = json.loads(config_path.read_text())
        assert isinstance(config, dict)

    def test_stable_ordering(self, sample_manifest, tmp_project: Path):
        manifest = load_manifest(tmp_project)
        target_config = manifest.targets["opencode"]
        generator = OpenCodeGenerator("opencode", target_config, manifest, tmp_project)

        # Generate twice
        generator.generate()
        content1 = (tmp_project / "AGENTS.md").read_text()

        generator.generate()
        content2 = (tmp_project / "AGENTS.md").read_text()

        # Content should be identical (stable ordering)
        assert content1 == content2
