"""Base generator interface."""

from abc import ABC, abstractmethod
from pathlib import Path

from agent_scaffold.models import CopilotTarget, Manifest, OpenCodeTarget


class BaseGenerator(ABC):
    """Abstract base class for target generators."""

    def __init__(
        self,
        target_name: str,
        target_config: OpenCodeTarget | CopilotTarget,
        manifest: Manifest,
        root: Path,
    ):
        """Initialize the generator.

        Args:
            target_name: Name of the target (e.g., 'opencode', 'copilot-vscode')
            target_config: Target configuration
            manifest: Full manifest
            root: Project root directory
        """
        self.target_name = target_name
        self.target_config = target_config
        self.manifest = manifest
        self.root = root

    @abstractmethod
    def generate(self, dry_run: bool = False) -> list[Path]:
        """Generate target files.

        Args:
            dry_run: If True, don't write files, just return what would be generated

        Returns:
            List of generated file paths
        """
        pass

    @abstractmethod
    def list_generated_files(self) -> list[Path]:
        """List all files this generator would create.

        Returns:
            List of file paths that would be generated
        """
        pass

    def banner(self, style: str = "html") -> str:
        """Return the 'generated by agent-scaffold' banner comment.

        Args:
            style: Comment style - 'html', 'yaml', or 'hash'

        Returns:
            Banner comment string
        """
        message = "Generated by agent-scaffold. Do not edit manually."
        if style == "html":
            return f"<!-- {message} -->\n"
        elif style == "yaml":
            return f"# {message}\n"
        else:
            return f"# {message}\n"
