"""OpenCode target generator."""

import json
from pathlib import Path

from agent_scaffold.generators.base import BaseGenerator
from agent_scaffold.models import OpenCodeTarget
from agent_scaffold.utils import ensure_dir


class OpenCodeGenerator(BaseGenerator):
    """Generator for OpenCode target files."""

    @property
    def config(self) -> OpenCodeTarget:
        """Get typed config."""
        return self.target_config  # type: ignore

    def list_generated_files(self) -> list[Path]:
        """List all files this generator would create."""
        files = []
        
        # opencode.json
        files.append(self.root / self.config.config_file)
        
        # AGENTS.md (if we're generating it - check if it's a "rules" project)
        # For now, we always generate it
        files.append(self.root / self.config.rules_index_file)
        
        return files

    def generate(self, dry_run: bool = False) -> list[Path]:
        """Generate OpenCode target files."""
        generated = []

        # Generate opencode.json
        config_path = self._generate_opencode_json(dry_run)
        if config_path:
            generated.append(config_path)

        # Generate AGENTS.md
        agents_md_path = self._generate_agents_md(dry_run)
        if agents_md_path:
            generated.append(agents_md_path)

        return generated

    def _generate_opencode_json(self, dry_run: bool) -> Path | None:
        """Generate the opencode.json configuration file."""
        config_path = self.root / self.config.config_file

        # Build the configuration object
        config: dict = {
            "$schema": "https://opencode.ai/config.json",
        }

        # Add instructions globs
        instructions_globs = [
            f"{self.manifest.paths.instructions_dir}/**/*.md",
        ]
        config["instructions"] = instructions_globs

        # Add commands
        for command in sorted(self.manifest.artifacts.commands, key=lambda c: c.id):
            # Check if this command is enabled for opencode
            command_targets = command.targets
            if "opencode" in command_targets:
                override = command_targets["opencode"]
                if not override.enabled:
                    continue

            # Build command config
            command_key = f"command.{command.id}"
            command_config: dict = {
                "description": command.description,
                "template": {"file": f"./{command.canonical_file}"},
            }

            # Add user input requirement if not default
            if command.user_input != "optional":
                command_config["userInput"] = command.user_input

            config[command_key] = command_config

        # Add agents
        for agent in sorted(self.manifest.artifacts.agents, key=lambda a: a.id):
            # Check if this agent is enabled for opencode
            agent_targets = agent.targets
            if "opencode" in agent_targets:
                override = agent_targets["opencode"]
                if not override.enabled:
                    continue
            
            # Build agent config
            agent_key = f"agent.{agent.id}"
            agent_config: dict = {}
            
            if agent.prompt_file:
                agent_config["prompt"] = {"file": f"./{agent.prompt_file}"}
            
            # Add overrides if present
            if "opencode" in agent_targets:
                override = agent_targets["opencode"]
                if hasattr(override, "model") and override.model:
                    agent_config["model"] = override.model
                if hasattr(override, "mode") and override.mode:
                    agent_config["mode"] = override.mode
                if hasattr(override, "temperature") and override.temperature is not None:
                    agent_config["temperature"] = override.temperature
                if hasattr(override, "steps") and override.steps is not None:
                    agent_config["steps"] = override.steps

            if agent_config:
                config[agent_key] = agent_config

        if not dry_run:
            ensure_dir(config_path.parent)
            content = json.dumps(config, indent=2)
            config_path.write_text(content, encoding="utf-8")

        return config_path

    def _generate_agents_md(self, dry_run: bool) -> Path | None:
        """Generate the AGENTS.md rules index file."""
        agents_md_path = self.root / self.config.rules_index_file

        lines = [
            "<!-- Generated by agent-scaffold. Do not edit manually. -->",
            "",
            "# AGENTS.md",
            "",
            f"> Configuration managed by agent-scaffold. See `.agents/manifest.yaml`.",
            "",
        ]

        # List instructions
        if self.manifest.artifacts.instructions:
            lines.append("## Instructions")
            lines.append("")
            for instruction in sorted(self.manifest.artifacts.instructions, key=lambda i: i.id):
                scope_label = f"({instruction.scope.value})" if instruction.scope else ""
                lines.append(f"- [{instruction.id}]({instruction.canonical_file}) {scope_label}")
            lines.append("")

        # List agents
        if self.manifest.artifacts.agents:
            lines.append("## Agents")
            lines.append("")
            for agent in sorted(self.manifest.artifacts.agents, key=lambda a: a.id):
                file_ref = agent.prompt_file or ""
                if file_ref:
                    lines.append(f"- [{agent.id}]({file_ref}) - {agent.description}")
                else:
                    lines.append(f"- {agent.id} - {agent.description}")
            lines.append("")

        content = "\n".join(lines)

        if not dry_run:
            ensure_dir(agents_md_path.parent)
            agents_md_path.write_text(content, encoding="utf-8")

        return agents_md_path
