"""Utility functions for agent-scaffold."""

import re
from pathlib import Path


def is_kebab_case(s: str) -> bool:
    """Check if a string is valid kebab-case (lowercase letters, numbers, hyphens)."""
    return bool(re.match(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$", s))


def to_kebab_case(s: str) -> str:
    """Convert a string to kebab-case."""
    # Replace underscores and spaces with hyphens
    s = re.sub(r"[_\s]+", "-", s)
    # Insert hyphens before uppercase letters and lowercase them
    s = re.sub(r"([a-z])([A-Z])", r"\1-\2", s)
    # Remove any non-alphanumeric characters except hyphens
    s = re.sub(r"[^a-zA-Z0-9-]", "", s)
    # Lowercase and remove leading/trailing hyphens
    return s.lower().strip("-")


def ensure_dir(path: Path) -> Path:
    """Ensure a directory exists, creating it if necessary."""
    path.mkdir(parents=True, exist_ok=True)
    return path


def generated_banner(style: str = "html") -> str:
    """Return the 'generated by agent-scaffold' banner comment.
    
    Args:
        style: Comment style - 'html', 'yaml', or 'json'
    
    Returns:
        Banner comment string with trailing newline
    """
    message = "Generated by agent-scaffold. Do not edit manually."
    if style == "html":
        return f"<!-- {message} -->\n"
    elif style == "yaml":
        return f"# {message}\n"
    elif style == "json":
        # JSON doesn't support comments, so we return empty string
        # The banner will be added as a field or omitted
        return ""
    else:
        return f"# {message}\n"


def relative_path(from_path: Path, to_path: Path) -> str:
    """Calculate relative path from one file to another.
    
    Args:
        from_path: The file we're creating the link in
        to_path: The file we're linking to
    
    Returns:
        Relative path string using forward slashes
    """
    try:
        # Get the directory containing from_path
        from_dir = from_path.parent
        rel = to_path.relative_to(from_dir.resolve())
        return str(rel).replace("\\", "/")
    except ValueError:
        # Files are on different drives or can't compute relative path
        # Fall back to path from project root
        return str(to_path).replace("\\", "/")
